input_beam:
  style: distgen     # from_file or distgen
  distgen_input_file: input/dipole_init_beam.yaml

input_lattice:
  lattice_input_file: input/dipole_lattice.yaml

particle_deposition:
  xbins: 100         # number of grids in x for particle deposition
  zbins: 100         # number of grids in y for particle deposition
  xlim: 5            # range in x in the unit of sigma_x
  zlim: 5            # range in z in the unit of sigma_z
  filter_order: 2    # 0 for no filter
  filter_window: 5
  velocity_threhold : 5

distribution_interpolation:
  xbins: 200
  zbins: 200
  xlim: 10
  ylim: 10
  re_interpolate_threhold: 2

CSR_integration:
  n_formation_length: 4
  zbins: 200
  xbins: 200

CSR_computation:
  compute_CSR: 1                 # if zero, only track the beam
  apply_CSR: 1                   # flag apply CSR to particles
  transverse_on: 1               # flag include transverse wake
  xbins: 20                    # The mesh on which CSR wake is computed
  zbins: 30
  xlim: 5
  zlim: 5
  write_beam: True
  write_wakes: True
  write_name: 'flatbeam_R1.5_exit'
  workdir: './output'














