name: Unit tests
on:
  pull_request:
  workflow_dispatch:
  push:
  schedule:
    - cron: "15 10 * * *"

permissions:
  contents: write

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ./.github/actions/conda-setup
      - name: Run unit tests
        shell: bash -l {0}
        run: |
          echo -e '## Test results\n\n```' >> "$GITHUB_STEP_SUMMARY"
          pytest -v 2>&1 | tee -a "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
